# Generated by Django 2.0.7 on 2023-05-25 07:58

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('BECHELOR', 'BECHELOR'), ('MASTER', 'MASTER')], max_length=30)),
                ('name_of_board_university', models.CharField(max_length=30, validators=[jobs.models.validate_name])),
                ('passing_year', models.IntegerField(validators=[jobs.models.validate_year])),
                ('percentage', models.IntegerField(validators=[jobs.models.validate_percentage])),
            ],
        ),
        migrations.CreateModel(
            name='CandidateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, validators=[jobs.models.validate_name])),
                ('lname', models.CharField(max_length=30, validators=[jobs.models.validate_name])),
                ('surname', models.CharField(max_length=30, validators=[jobs.models.validate_name])),
                ('contact_no', models.CharField(max_length=10, validators=[jobs.models.validate_contact_no])),
                ('city', models.CharField(max_length=30, validators=[jobs.models.validate_name])),
                ('state', models.CharField(max_length=30, validators=[jobs.models.validate_name])),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30)),
                ('dob', models.DateField(validators=[jobs.models.validate_dob])),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, validators=[jobs.models.validate_name])),
                ('designation', models.CharField(max_length=50, validators=[jobs.models.validate_name])),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CandidateMaster')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageKnownMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('read', models.NullBooleanField()),
                ('write', models.NullBooleanField()),
                ('speak', models.NullBooleanField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CandidateMaster')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_location', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Rajkot', 'Rajkot')], max_length=30)),
                ('notice_period', models.IntegerField(validators=[jobs.models.validate_notice_period])),
                ('expected_ctc', models.IntegerField()),
                ('current_ctc', models.IntegerField()),
                ('department', models.CharField(choices=[('Development', 'Development'), ('Design', 'Design'), ('HR', 'HR'), ('Testing', 'Testing')], max_length=30)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CandidateMaster')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refe_name', models.CharField(max_length=50, validators=[jobs.models.validate_name])),
                ('refe_contact_no', models.CharField(max_length=10, validators=[jobs.models.validate_contact_no])),
                ('refe_relation', models.CharField(max_length=30, validators=[jobs.models.validate_name])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CandidateMaster')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyKnownMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(blank=True, max_length=30, null=True)),
                ('ranting', models.IntegerField(blank=True, null=True, validators=[jobs.models.validate_rating])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CandidateMaster')),
            ],
        ),
        migrations.AddField(
            model_name='academicmaster',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CandidateMaster'),
        ),
    ]
